# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 813d08aa-0aee-4e6a-a509-2cbe85d75bbb

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      vohmin77@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="813d08aa-0aee-4e6a-a509-2cbe85d75bbb"